---
- hosts: test
  gather_facts: no
  become: yes
  tasks:
  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add sudoers user2 to wheel group
    user:
      name=user2
      groups=wheel
      append=yes
      state=present
      createhome=yes

  - name: Add sudoers user3 to wheel group
    user:
      name=user3
      groups=wheel
      append=yes
      state=present
      createhome=yes

  - name: creating a directory for user2
    file:
      path: /home/user2/.ssh/
      state: directory

  - name: creating a directory for user3
    file:
      path: /home/user3/.ssh/
      state: directory

  - name: Set up authorized keys for the user2
    authorized_key: user=user2 key="{{item}}"
    with_file:
      - /home/user2/.ssh/id_rsa.pub

  - name: Set up authorized keys for the user3
    authorized_key: user=user3 key="{{item}}"
    with_file:
      - /home/user3/.ssh/id_rsa.pub
